// Generated by `cargo run -p ac-protocol --bin gen-typescript -- protocol` from the Rust types in
// crates/protocol (ADR-0036): change the Rust, not this file.
/**
 * The wire shapes (CONTEXT.md: Wire shape): every message between engine and
 * Console, declared once. The Console type-imports them (`import type` only),
 * which makes drift between the two a compile error rather than a silent copy.
 */

// ---------------------------------------------------------------------------
// Ticket events
// ---------------------------------------------------------------------------

/** One line of a Ticket's events file, as GET /api/events serves it. */
export interface TicketEvent {
  at: string;
  attempt: number;
  kind: TicketEventKind;
  payload: Record<string, unknown>;
}

/** What a Ticket event records. */
export type TicketEventKind =
  | "scheduled"
  | "spawned"
  /**
   * A terminal-backed launch whose wrapper never ran (issue #102's Botched
   * launch): the tab it was typed into, closed, and the reason; the launch
   * went on into a fresh tab, and only the tab it ended up in is `spawned`.
   */
  | "launch-retried"
  | "exited"
  | "merged"
  | "merge-conflict"
  /**
   * A merge git refused before starting (#92): untracked files in the pool
   * checkout that differ from the branch's version stood in its way.
   * Nothing conflicted and no resolver runs; the operator clears the way.
   */
  | "merge-blocked"
  | "resolver"
  | "graded"
  | "selected"
  | "grader-respawn"
  | "checkpoint"
  | "crash"
  | "deadlock"
  | "deadlock-cleared"
  | "answered"
  | "review-reject"
  | "spawn-adopted"
  | "spawn-rejected"
  /**
   * Proposals within the caps, taken from the attempt and waiting for the
   * next boundary to land (issue #150): each one's proposal id and title.
   */
  | "spawn-pending"
  /**
   * Proposals held for the operator rather than landed (ADR-0029, issue
   * #150): each one's proposal id, title and reason, a cap that had no room
   * (`per-attempt`, `per-run`), the agent's own `overlaps` mark (with the
   * ids it named) or the operator's Hold (`operator`); `recovered` when
   * boot held proposals a pre-ADR cap had truncated.
   */
  | "spawn-held"
  /**
   * A Held or Pending spawn the operator discarded (ADR-0029, issue #150),
   * by id and title, `pending` when it had not yet been held.
   */
  | "spawn-discarded"
  | "reassigned"
  /**
   * The ticket file's two copies (the pool's file of record and the
   * worktree seed the agent committed) changed the same lines differently,
   * so the reconcile at merge left conflict markers in the file of record.
   */
  | "ticket-file-conflict"
  /**
   * An operator-ended Conversation's closing record (the Conversations ADR,
   * docs/adr/0018-conversations-beside-tickets.md): merged, ended with no
   * commits, or ended with its branch parked on a rejected merge-approval.
   */
  | "ended"
  /**
   * A Turn the engine typed into a waiting parent Conversation reporting
   * something it spawned finishing.
   */
  | "notice"
  /**
   * A Notice that never delivered (the parent ended or crashed first, or
   * the queue was still non-empty at End), logged on the child's own file
   * instead.
   */
  | "notice-dropped"
  /**
   * The ticket's solo branch is checked out in a directory the engine does
   * not own (issue #101: the checkout an enlist moved onto its created pool
   * branch), so no worktree could be opened and the ticket waits as a
   * checkpoint until the branch is free.
   */
  | "branch-held"
  /**
   * The ticket was about to schedule with no harness or model (issue #118:
   * a spawn off an enlisted Conversation, or a pool with no defaults), so
   * it waits as a config interrupt instead of a launch that would throw.
   */
  | "unassigned"
  /**
   * A tab the engine closed by rule (a merge, a role's end, a Conversation's
   * end, a Resume's fresh launch, the operator's bulk close) that herdr
   * refused to close (issue #139): the close stays best-effort, and this is
   * the record that it failed and why, where a silent catch used to be.
   */
  | "tab-close-failed"
  /**
   * The engine closed the tab of a checkpointed Attempt before a Resume's
   * fresh launch (issue #139): recorded so the close happens once and a
   * later Resume never reaches back for a tab it already closed.
   */
  | "tab-closed"
  /**
   * An enlisted pane the pool let go (issue #139): an abandoned adoption
   * left it exactly as found and handed the Ticket back to ordinary
   * attempts, so a restart must not take the pane back as the Ticket's.
   */
  | "let-go"
  /**
   * The operator asked a Conversation to End (issue #140): recorded before
   * the End moves anything, so an engine that stops mid-End leaves the next
   * boot the fact that this was an ending, not a crash.
   */
  | "end-requested"
  /**
   * A merge a shutdown dropped while it waited at the pool checkout's gate
   * (issue #139, ADR-0027): the worktree and branch it would have merged,
   * so the next boot chains it again through the ordinary merge path.
   */
  | "merge-deferred"
  /**
   * The Steward (ADR-0030) left a pending Interrupt to the operator: the
   * Interrupt's kind and the Steward note, its recommendation, with `by`
   * and the Steward's `conversation`. Never counts against its budget.
   */
  | "steward-note"
  /**
   * The Steward wrote this Ticket's assign entry (ADR-0030): the fields it
   * set or cleared, with `by` and `conversation`. The engine's own
   * `reassigned` follows at the next Config reload, as for the operator's.
   */
  | "reassign-requested";

// ---------------------------------------------------------------------------
// Conversations
// ---------------------------------------------------------------------------

/** Where a Conversation stands. */
export type ConversationStatus = "live" | "ended" | "crashed";

/** Which side of its Turn a Conversation is on. */
export type TurnSide = "working" | "waiting";

/** The roles a Conversation may carry. Absent is an ordinary Conversation. */
export type ConversationRole = "steward";

/** A Conversation as the snapshot carries it (conversations.ts's viewOf). */
export interface ConversationView {
  id: string;
  title: string;
  status: ConversationStatus;
  spawnedBy: string | null;
  assignment: AssignmentView;
  paneId: string | null;
  branch: string | null;
  turn: { state: TurnSide; lastLine: string; idleSince: string | null };
  children: string[];
  /**
   * Enlisted from a live herdr pane (issue #101): the card reads "as found"
   * where a started Conversation names its model.
   */
  enlisted: boolean;
  /**
   * Its End is under way (issue #140): the talk is over and its tab closed
   * or closing, the merge still to land. The Console shows it ending with
   * End disabled, and `paneId` is null so nothing peeks or focuses a pane
   * that is going.
   */
  ending: boolean;
  /** The Steward (ADR-0030): present only on a Conversation in that role. */
  role?: ConversationRole;
  /**
   * Notices are not reaching this pane: present from the first failed
   * delivery until one lands. The Turn state may still read waiting, since
   * a Blocking dialog in the pane looks idle while it swallows every Turn,
   * and the engine answers no dialog but Folder trust; the operator has to
   * look at the pane.
   */
  delivery?: NoticeDelivery;
}

/**
 * A Conversation whose Notices keep failing to land (ADR-0030's live e2e):
 * since when, and why the last try failed. Turn state can read "waiting"
 * while something in the pane (a Blocking dialog the engine never answers)
 * swallows every Turn, so the failure is shown rather than retried
 * invisibly. Cleared by the first Notice that lands.
 */
export interface NoticeDelivery {
  failingSince: string;
  lastError: string;
}

/** POST /api/conversations's body: start a Conversation. */
export interface StartConversationRequest {
  title: string;
  opening?: string;
  /**
   * Start it as the Steward (ADR-0030): `opening` is then the operator's
   * standing orders, and its Assignment comes from the Steward entry of
   * the Pool settings ahead of the pool defaults.
   */
  role?: ConversationRole;
  assign?: { harness?: string; model?: string; effort?: string; drivers?: string };
  spawnedBy?: string;
  /**
   * Spawn adoption precomputes a collision-free id shared across a parent's
   * ticket-spawn and Conversation-spawn counters and passes it here, used
   * verbatim. Absent for every operator-started Conversation, whose id the
   * engine mints.
   */
  id?: string;
}

// ---------------------------------------------------------------------------
// The run, Interrupts, Outcomes and Grades
// ---------------------------------------------------------------------------

/** The two Evidence budgets a Jev Grade can record. */
export type EvidenceBudget = "base" | "widened";

/**
 * One assessment of one attempt (the Grade in CONTEXT.md): the score, the
 * verdict, and short reasons, landed on the graded attempt's record. An agent
 * grader carries it in its Outcome JSON under a `grade` key; a Jev-graded
 * Grade is composed in engine code (ADR-0023). The three provenance fields a
 * Jev Grade adds are optional: an agent-graded Grade has none.
 */
export interface Grade {
  score: number;
  verdict: "pass" | "flag";
  reasons: string;
  /** The rubric version that composed it, e.g. `jev-grader-rubric/2026-09-20.1`. */
  rubric?: string;
  /** The model the API reported it answered with. */
  model?: string;
  /** Which Evidence budget the Grade came from: the base one or the widening re-ask. */
  evidenceBudget?: EvidenceBudget;
}

/**
 * A question the run puts to the operator. The Conversation module raises
 * its own merge interrupts in this shape too.
 */
export interface Interrupt {
  ticketId: string;
  kind: InterruptKind;
  body: string;
  /**
   * A selection interrupt's candidate attempt numbers, riding so the answer
   * is validated against the exact fan-out the grades came from, including
   * after a restart (a superseded round's graded attempts would otherwise
   * pass for candidates).
   */
  candidates?: number[];
  /**
   * The Steward note on it (ADR-0030), on the snapshot's copy only: the
   * Steward left this Interrupt to the operator with this recommendation.
   * Never persisted with the Interrupt; steward.ts's store keeps it.
   */
  stewardNote?: StewardNote;
}

/** What an Interrupt asks. */
export type InterruptKind =
  | "checkpoint"
  | "config"
  | "crash"
  | "deadlock"
  | "merge-conflict"
  | "merge-approval"
  | "persistence"
  | "review"
  | "selection";

/**
 * The attempt's result, written by the agent as JSON at the outcome path its
 * prompt names and read by the engine at attempt exit.
 */
export interface Outcome {
  status: OutcomeStatus;
  summary: string;
  commitSha: string | null;
  brief?: string;
  /**
   * Follow-up ticket proposals (ADR-0010): the agent proposes in its Outcome,
   * the engine writes the pool at the super-step boundary. Three states:
   * absent, the attempt proposed nothing; present and empty, the key was
   * there and nothing survived schema validation; populated, the
   * well-formed proposals riding to the boundary.
   */
  spawn?: SpawnProposal[];
}

/**
 * The attempt's ending: the engine, not the agent, writes it to the canonical
 * Issue's line-1 marker (ADR-0005).
 */
export type OutcomeStatus = "done" | "checkpoint";

/**
 * One follow-up ticket an attempt proposes in its Outcome's optional spawn
 * array (ADR-0010). The agent never proposes an id, a status or a marker:
 * the engine assigns the id, writes the ticket file and owns the marker.
 */
interface SpawnProposal {
  title: string;
  body: string;
  blockedBy?: string[];
  /**
   * What the proposal becomes. Absent means "ticket", ADR-0010's original
   * shape; "conversation" starts a child Conversation instead of writing a
   * ticket file.
   */
  kind?: "ticket" | "conversation";
  /**
   * The child's Assignment, when the proposer wants something other than
   * its own. Absent inherits. A ticket child keeps it on its marker as
   * spawn-assign (issue #116), ranked under the operator's assign entry.
   */
  assign?: SpawnAssignRequest;
  /**
   * Set by validation when the proposal's assign named a verify, which no
   * proposal may set (grading is the operator's call, issue #116): the
   * proposal lands without it, and the engine logs that once and strips
   * this flag before the proposal is stored.
   */
  verifyIgnored?: true;
  /**
   * The tickets the Spawn blocks once adopted (ADR-0029): named ids, or
   * "all" for every ticket not yet started at that moment.
   */
  blocks?: string[] | "all";
  /**
   * The pool work the proposing agent read in the Spawn ledger and judged
   * this proposal to overlap (issue #150): Tickets, Conversations, or
   * Pending or Held spawns, by id. A proposal that names any is held for
   * the operator to decide instead of landing.
   */
  overlaps?: string[];
}

/**
 * A Spawn proposal's Assignment request (issue #116): the fields a proposal's
 * `assign` may set, persisted on the spawned Ticket's marker. Never verify:
 * whether a Ticket is graded stays the operator's call.
 */
interface SpawnAssignRequest {
  harness?: string;
  model?: string;
  effort?: string;
  drivers?: string;
}

/**
 * The phases a run reports. `dead` is terminal and distinct from the closing
 * gate's done/quiescent/stalled: it is emitted only when an error the drive
 * truly cannot continue from has killed the loop. `stopped` is the other
 * terminal phase and the only one the drive never emits: the shutdown emits
 * it once, as the farewell frame, after the children are stopped and the
 * store closed (issue #97), so a Console tab can tell an orderly stop from a
 * dead drive and from a lost connection.
 */
export type RunPhase = "running" | "done" | "quiescent" | "stalled" | "dead" | "stopped";

/**
 * What the Console shows of the Spawn caps: `spawnedThisRun` of `perRun`
 * this run, and `perAttempt` per attempt.
 */
export interface SpawnUsage {
  spawnedThisRun: number;
  perAttempt: number;
  perRun: number;
}

/** The pool's console.json as the engine reads it. */
export interface PoolConfig {
  defaults?: AssignmentDefaults;
  assign?: Record<string, TicketAssignment>;
  /**
   * The merge resolver: a harness name (the model is inherited from
   * defaults), "none" to opt out, or { harness, model, effort } when the
   * resolver runs on a harness other than the defaults', whose model names
   * (and effort words) would not be recognised there.
   */
  resolver?: string | { harness?: string; model?: string; effort?: string };
  port?: number;
  /**
   * The Spawn caps (ADR-0029): absent fields take the defaults, 5 per
   * attempt and 20 per run.
   */
  spawnCaps?: SpawnCapsConfig;
  /**
   * Who picks the winner of a verify fan-out: the engine's arithmetic rule
   * (default) or the human, via a selection interrupt carrying the grades.
   */
  selection?: "auto" | "human";
  /**
   * Terminal backing for every attempt (ADR-0014, ADR-0015): "herdr" opens a
   * named herdr tab per attempt and records its pane id on the spawned
   * event. Absent means headless.
   */
  terminal?: "herdr";
  /**
   * Prose the setup skill writes here and the engine never reads: agents meet
   * it through the pool's AGENT.md. Declared so the Settings pane (issue
   * #121) edits it as a Pool setting rather than as an unknown key.
   */
  reviewer?: string;
  checkpoint?: string;
  /**
   * The Pool title (issue #100): one line the operator gives the pool so
   * several can be told apart. Display-only: the directory stays the pool's
   * identity.
   */
  title?: string;
  /**
   * The Steward entry (ADR-0030): the Steward budget, 5 unless set, and the
   * Steward's Assignment, ahead of the pool defaults.
   */
  steward?: StewardConfig;
}

/** The pool defaults' Assignment fields: console.json `defaults`. */
interface AssignmentDefaults {
  harness?: string;
  model?: string;
  effort?: string;
  drivers?: string;
}

/** One Ticket's console.json `assign` entry. */
interface TicketAssignment {
  harness?: string;
  model?: string;
  effort?: string;
  drivers?: string;
  verify?: number;
}

/** The Spawn caps as console.json carries them: either field may be absent. */
interface SpawnCapsConfig {
  perAttempt?: number;
  perRun?: number;
}

// ---------------------------------------------------------------------------
// Tickets, Assignments and live Attempts
// ---------------------------------------------------------------------------

/** A Ticket's status, as its line-1 marker records it. */
export type TicketStatus = "ready" | "in-progress" | "done" | "checkpoint" | "closed";

/**
 * One resolved Assignment on the wire (ADR-0013): the engine's record with
 * no verify (Verify keeps its own surfaces) and the engine's empty string
 * rendered as null for an unassigned field. The UI renders this record
 * verbatim; nothing re-derives it.
 */
export interface AssignmentView {
  harness: string | null;
  model: string | null;
  /**
   * Present only when some layer sets one; absent, the harness runs on its
   * own default.
   */
  effort?: string;
  /**
   * Present beside an effort only: whether the harness, in the mode it
   * launches in, can take it. False renders the effort as not applied.
   */
  effortApplied?: boolean;
  drivers: string;
}

/**
 * What a live Attempt is doing for its Ticket (issue #129): the Ticket's own
 * work, or a resolver staging the resolution of its conflicted merge. A
 * done card with a live resolver is a merge being resolved, not a Ticket
 * re-running, and the Console says so only because the engine says so here.
 */
export type AttemptRole = "agent" | "resolver";

/** One live Attempt as the snapshot carries it; `tabId` stays engine-side. */
export interface LiveAttemptRecord {
  attempt: number;
  /** The herdr pane the Attempt runs in; null when headless. */
  paneId: string | null;
  role: AttemptRole;
  /**
   * When the engine registered the Attempt live (ISO): the Console ticks
   * the elapsed time from it client-side, so no emit is spent on a clock.
   */
  startedAt: string;
}

/** A Held pane as the snapshot carries it; the rest stays engine-side. */
export interface HeldPaneRecord {
  /** The checkpointed Attempt whose pane this is. */
  attempt: number;
  paneId: string;
}

// ---------------------------------------------------------------------------
// Spawn proposals
// ---------------------------------------------------------------------------

/**
 * Why a proposal is held: which cap had no room (the attempt's, or a
 * spawn.json's, own; or the run's), the proposing agent's own `overlaps`
 * mark (the ids ride on the proposal), the operator's Hold of a Pending
 * spawn, or a Pending spawn the boundary refused to land because the pool
 * moved after it was taken (the reason rides as `adoptError`).
 */
export type HeldSpawnReason = "per-attempt" | "per-run" | "overlaps" | "operator" | "refused";

/**
 * One Pending spawn as the Console shows it: a proposal within the caps that
 * lands at the next super-step boundary unless the operator Holds or
 * Discards it first.
 */
export interface PendingSpawnView {
  id: string;
  parentId: string;
  origin: "ticket" | "conversation";
  /** What landing it starts: a Ticket, or a Conversation. */
  kind: "ticket" | "conversation";
  title: string;
  body: string;
  blockedBy: string[];
  /**
   * The tickets it would block once it lands, "all" for every ticket not
   * yet started at that moment, or null when it blocks none.
   */
  blocks: string[] | "all" | null;
  /**
   * The pool work the proposing agent said it overlaps: Tickets,
   * Conversations, or other proposals, by id. Empty when it named none.
   */
  overlaps: string[];
  at: string;
}

/** One held spawn as the Console shows it. */
export interface HeldSpawnView {
  id: string;
  parentId: string;
  origin: "ticket" | "conversation";
  /** What landing it starts: a Ticket, or a Conversation. */
  kind: "ticket" | "conversation";
  title: string;
  body: string;
  blockedBy: string[];
  /**
   * The tickets it would block once it lands, "all" for every ticket not
   * yet started at that moment, or null when it blocks none.
   */
  blocks: string[] | "all" | null;
  /**
   * The pool work the proposing agent said it overlaps: Tickets,
   * Conversations, or other proposals, by id. Empty when it named none.
   */
  overlaps: string[];
  at: string;
  reason: HeldSpawnReason;
  /**
   * The ids an "overlaps" hold named that the pool never knew; empty when
   * every one was known.
   */
  unknownOverlaps: string[];
  /**
   * An Adopt is on its way to the boundary: the spawn is still held until
   * the engine writes it, so a restart before then loses nothing.
   */
  adopting: boolean;
  /**
   * Why the boundary refused to land it (a blocker gone, a blocks target
   * finished while it waited): the spawn stayed held, or, for "refused",
   * was held instead of landing. Absent until a refusal, and cleared by
   * the next Adopt.
   */
  adoptError?: string;
}

// ---------------------------------------------------------------------------
// The Merge queue and Queued answers
// ---------------------------------------------------------------------------

/** One held ticket in the Merge queue, as the snapshot carries it. */
export interface MergeQueueEntry {
  ticketId: string;
  state: MergeQueueState;
}

/**
 * Where one held ticket's merge stands (CONTEXT.md: Merge queue). The first
 * three are a head, a merge that is moving: a resolver on it (or the engine
 * launching one), or the operator's answer awaited at a merge-approval or a
 * merge-conflict interrupt. `queued` is behind the engine's own work, with
 * nothing running on its behalf. `stalled` is held with none of those: no
 * resolver, no interrupt, and no merge the engine has taken on and not yet
 * finished with (issue #87's case, named here, not fixed).
 */
export type MergeQueueState =
  | "resolving"
  | "awaiting-approval"
  | "needs-you"
  | "queued"
  | "stalled";

/** An accepted answer waiting for processing at the next super-step boundary (a Queued answer). */
export interface QueuedAnswer {
  ticketId: string;
  /** The interrupt identity: the kind of interrupt this answer addresses. */
  kind: InterruptKind;
  /** The answer payload: true approve, false reject, absent resume. */
  approve?: boolean;
  /**
   * A Close (issue #154): the ticket is dropped without merging. An Adopt
   * (ADR-0035): one finished Candidate of a paused verify round is taken as
   * the Winner. Absent on every other answer, so a file written before
   * either existed reads as it always did.
   */
  action?: "close" | "adopt";
  /** The Candidate an Adopt takes; present only with `action: "adopt"`. */
  attempt?: number;
  note?: string;
  /** The Steward gave it (ADR-0030); absent is the operator's. */
  by?: AnswerBy;
  at: string;
  seq: number;
  processedAt: string | null;
}

/**
 * Who gave an answer, as the Ticket log records it. An `answered` event with
 * no `by` is the operator's: every answer written before the Steward existed
 * reads that way unchanged.
 */
export type AnswerBy = "operator" | "steward";

// ---------------------------------------------------------------------------
// Enlist
// ---------------------------------------------------------------------------

/** One live herdr pane, as the picker lists it. */
export interface EnlistPane {
  paneId: string;
  /** herdr's agent label: the harness, or null when none is bound. */
  harness: string | null;
  /** herdr's agent status: idle, working, blocked, done or unknown. */
  status: string;
  /** The pane's terminal title. */
  title: string;
  /** The pane's working directory, or null when herdr reports none. */
  directory: string | null;
  /**
   * The branch checked out in `directory`, resolved by the engine; null
   * when the directory is not a checkout.
   */
  branch: string | null;
  eligible: boolean;
  /** Why the pane cannot be enlisted; null when it can. */
  reason: string | null;
}

/**
 * The panes response envelope: every pane `agent.list` reports, eligible or
 * not, with the reason beside the ineligible ones.
 */
export interface PanesResponse {
  panes: EnlistPane[];
}

/**
 * The enlist request body (issue #101), declared once here so the server
 * route and the Console type-import the same shape. `becomes` is fixed at
 * enlist time, and one of the arms is chosen from it: a Ticket, a
 * Conversation, or a Conversation as the Steward (ADR-0030). The engine
 * re-judges the pane at submit rather than trusting a picker read that may
 * be stale. The branch is never on the wire: the engine resolves the found
 * directory's branch with git and applies the branch rule itself.
 */
export type EnlistRequest =
  | EnlistTicketRequest
  | EnlistConversationWireRequest
  | EnlistStewardWireRequest;

/** Enlist a pane as a Ticket. */
interface EnlistTicketRequest {
  becomes: "ticket";
  paneId: string;
  title: string;
  spec: string;
  /** The unfinished tickets that must wait on the enlisted one. */
  blocks?: string[];
}

/** Enlist a pane as a Conversation. */
interface EnlistConversationWireRequest {
  becomes: "conversation";
  paneId: string;
  title: string;
  /** The optional first Turn, typed after the teaching Turn. */
  opening?: string;
}

/**
 * Enlist as the Steward (ADR-0030): a Conversation in that role, refused
 * while a Steward is already on duty. The opening, when given, is the
 * operator's standing orders, typed after the Steward's teaching Turn.
 */
export interface EnlistStewardWireRequest {
  becomes: "steward";
  paneId: string;
  /** Optional: "Steward" when blank. */
  title?: string;
  opening?: string;
}

/** The enlist answer: the minted id, a 201 on success. */
export type EnlistResponse = { ticketId: string } | { conversationId: string };

// ---------------------------------------------------------------------------
// The Steward
// ---------------------------------------------------------------------------

/** The answer every Steward write route gives: what was done, in one line. */
export interface StewardActionResponse {
  ok: true;
  message: string;
}

/** POST /api/steward/answer: the operator's answer path, as the Steward's. */
export interface StewardAnswerRequest {
  conversation: string;
  ticketId: string;
  action: "resume" | "approve" | "reject" | "close";
  note?: string;
}

/** The Steward's Assignment fields, each optional, layered ahead of the pool defaults. */
export interface StewardAssign {
  harness?: string;
  model?: string;
  effort?: string;
  drivers?: string;
}

/**
 * The budget as the snapshot carries it: the Pool's, and what the Steward
 * has used per Ticket (only Tickets it has answered since the operator
 * last did).
 */
export interface StewardBudgetView {
  budget: number;
  used: Record<string, number>;
}

/** console.json `steward`: the Steward budget, the Steward's Assignment, and whether it may Close. */
export interface StewardConfig {
  budget?: number;
  assign?: StewardAssign;
  /** "Steward may Close checkpoints" (issue #154, ADR-0033): off unless true. */
  mayClose?: boolean;
}

/** POST /api/steward/end: the Steward ends itself, closing line included. */
export interface StewardEndRequest {
  conversation: string;
  closing?: string;
}

/** POST /api/steward/held: Adopt or Discard a Held spawn. */
export interface StewardHeldRequest {
  conversation: string;
  action: "adopt" | "discard";
  id: string;
}

/** POST /api/steward/keep-talking: Keep talking, then the message typed after the teaching Turn. */
export interface StewardKeepTalkingRequest {
  conversation: string;
  ticketId: string;
  message: string;
}

/** POST /api/steward/leave: leave a pending Interrupt to the operator with a Steward note. */
export interface StewardLeaveRequest {
  conversation: string;
  ticketId: string;
  note: string;
}

/** A Steward note as the snapshot's interrupt carries it. */
export interface StewardNote {
  text: string;
  at: string;
  /** The Steward that wrote it. */
  conversation: string;
}

/** POST /api/steward/reassign: Reassign's own body (ReassignRequest), as the Steward's. */
export interface StewardReassignRequest {
  tickets: string[];
  fields: {
    harness?: string | null;
    model?: string | null;
    effort?: string | null;
    drivers?: string | null;
    verify?: number | null;
  };
  conversation: string;
}

/** One pending Interrupt as the Steward's state read shows it. */
export interface StewardStateInterrupt {
  ticketId: string;
  title: string | null;
  kind: string;
  /** Whether the Steward may answer it at all (not review, persistence or a Conversation's). */
  answerable: boolean;
  keepTalking: boolean;
  /** An answer is already queued for it. */
  queued: boolean;
  /** The Steward's own note, when it left the Interrupt. */
  note: string | null;
  used: number;
  remaining: number;
}

/** GET /api/steward/state?conversation=<id>: a compact read of what the Steward stewards. */
export interface StewardStateResponse {
  steward: string;
  budget: number;
  /** "Steward may Close checkpoints", read live from the pool settings. */
  mayClose: boolean;
  phase: string;
  interrupts: StewardStateInterrupt[];
  mergeQueue: { ticketId: string; state: string }[];
  pendingSpawns: { id: string; parentId: string; title: string }[];
  heldSpawns: { id: string; parentId: string; title: string; reason: string }[];
  /** The Spawn ledger, for the whole pool's state in one file. */
  ledger: string;
}

// ---------------------------------------------------------------------------
// The Settings pane
// ---------------------------------------------------------------------------

/** PUT /api/settings/machine. The defaults are written whole. */
export interface MachineDefaultsRequest {
  defaults: MachineDefaults;
}

/**
 * The machine's half: `defaults` is what is in force (the legacy runner
 * files filled in), `own` is only the JSON file's own fields, which is what
 * the pane edits and writes back.
 */
export interface MachineDefaultsView {
  path: string;
  defaults: MachineDefaults;
  own: MachineDefaults;
}

/** The Machine defaults file: what every new pool starts with. */
export interface MachineDefaults {
  harness?: string;
  model?: string;
  /** The harness's own effort word (CONTEXT.md: Effort), passed through verbatim. */
  effort?: string;
  drivers?: string;
  /** The agent-console checkout Boot runs the engine from. */
  engine?: string;
  /** Terminal backing every new pool starts with; the only legal value is "herdr". */
  terminal?: "herdr";
}

/**
 * PUT /api/settings/pool. The patch is a partial PoolConfig; a key set to
 * null or "" removes it.
 */
export interface PoolSettingsRequest {
  config: Record<string, unknown>;
}

/**
 * The Pool's half of the Settings payload. `effective` is what THIS process
 * booted with, so the Console can badge a boot-only key whose saved value no
 * longer matches what is running.
 */
export interface PoolSettingsView {
  path: string;
  /** The pool's console.json as parsed, unknown keys included, `{}` when absent. */
  config: PoolConfig;
  bootOnly: string[];
  effective: {
    port: number;
    terminal: "herdr" | null;
    /**
     * The boot-only keys whose saved value is not what is running, so the
     * badge survives a reload and catches a hand edit, not only a save made
     * in this tab. A subset of `bootOnly`.
     */
    stale: string[];
  };
}

/**
 * POST /api/restart's acknowledgement: the port the relaunched Console will
 * listen on, so the tab knows where to reconnect when it moved.
 */
export interface RestartResponse {
  ok: true;
  /**
   * console.json's own `port` as written when it is set and not 0, else the
   * bound port: unchecked, as the TypeScript re-reads it.
   */
  port: number;
}

/** The Settings pane's payload: GET /api/settings and both PUTs answer with it. */
export interface SettingsResponse {
  pool: PoolSettingsView;
  machine: MachineDefaultsView;
  /** The harness names this pool knows, sorted, for the pane's pickers. */
  harnesses: string[];
}

// ---------------------------------------------------------------------------
// Reassign
// ---------------------------------------------------------------------------

/**
 * Where one resolved field came from (Reassign, issue #126): the unit's own
 * request layer (a Ticket's `assign` entry, so the Console calls it pinned),
 * a spawned Ticket's requested Assignment (its proposal's `assign`, issue
 * #116), what it inherits from its parent or build ticket, the pool
 * defaults, or nowhere at all.
 */
export type AssignmentSource = "pinned" | "requested" | "inherited" | "default" | "unset";

/** Where each field of a ticket's Assignment came from. */
export interface AssignmentSources {
  harness: AssignmentSource;
  model: AssignmentSource;
  effort: AssignmentSource;
  drivers: AssignmentSource;
}

/**
 * The write body (PUT /api/reassign). `tickets` names the ids to change;
 * `fields` is tri-state per field: a key absent leaves that field alone,
 * a value sets it, and null clears the ticket's own entry for it so the
 * ticket follows its parent or the pool defaults again. `verify` is an
 * integer >= 1 or null to clear.
 */
export interface ReassignRequest {
  tickets: string[];
  fields: {
    harness?: string | null;
    model?: string | null;
    effort?: string | null;
    drivers?: string | null;
    verify?: number | null;
  };
}

/**
 * The write's answer. A refused write (unknown ticket, unknown harness,
 * bad verify, or a ticket that would end up unassigned) is a 400 with
 * `{ error }` naming the ticket and nothing is written. Otherwise every
 * named ticket that is still eligible is written in one atomic file
 * replace and listed in `applied`; a ticket that stopped being eligible
 * between listing and saving is left alone and listed in `skipped` with
 * its reason. `snapshot` is the fresh enriched snapshot after the write, so
 * the Console pushes it through setSnapshot and the cards show the new
 * Assignment at once.
 */
export interface ReassignResponse {
  applied: string[];
  skipped: { id: string; reason: string }[];
  snapshot: EnrichedSnapshot;
}

/**
 * The per-ticket Reassign view the snapshot carries on every ordinary
 * ticket (grader and head-to-head tickets are never reassignable and carry
 * `eligible: false` with a reason). `eligible` is the server's judgement
 * that a write would take effect at the next boundary: no Attempt in
 * flight and not done. `reason` explains a false `eligible` in one line
 * for the Detail pane. `verify` is the ticket's own verify count, which
 * has no default and so is pinned or absent. `sources` explains the
 * Assignment the card shows.
 */
export interface TicketReassignView {
  eligible: boolean;
  reason: string | null;
  verify: number | null;
  sources: AssignmentSources;
}

// ---------------------------------------------------------------------------
// Resume (POST /api/resume)
// ---------------------------------------------------------------------------

/**
 * The action a resume request carries (POST /api/resume): `approve` and
 * `reject` answer the review gate and merge-approval interrupts; `close`
 * drops a ticket at a checkpoint, merge-conflict or deadlock Interrupt
 * without merging it (issue #154); `adopt` takes one finished Candidate of
 * a paused verify round as the Winner, named by the request's `attempt`
 * (ADR-0035); plain `resume` answers every other kind. Declared once here;
 * the server's answer path and the Console's client and interrupt forms all
 * use it.
 */
export type ResumeAction = "resume" | "approve" | "reject" | "close" | "adopt";

// ---------------------------------------------------------------------------
// The snapshot (GET /api/state, POST /api/start and /api/resume, the socket)
// ---------------------------------------------------------------------------

/** One ticket as the enriched snapshot carries it. */
export interface EnrichedTicketState {
  id: string;
  title: string;
  blockedBy: string[];
  status: TicketStatus;
  /**
   * Where the ticket stands in the Merge queue (issue #129): null unless
   * it is done and its branch has not landed in the merge target
   * (ADR-0014). A lookup into the snapshot's Merge queue, the engine's one
   * derivation; every UI surface reads this field and never git.
   */
  mergeState: MergeQueueState | null;
  /** The ticket's resolved Assignment record (ADR-0013), served verbatim. */
  assignment: AssignmentView;
  /**
   * The ticket's Live attempt (ADR-0014): the attempt number and, for a
   * terminal-backed attempt, its herdr pane, served verbatim from the
   * engine's snapshot while the attempt runs; null once it has ended, so a
   * finished card's terminal surface and its polling stop, and null for a
   * ticket with nothing running. A headless attempt is live with a null
   * pane. Its role says whether it is the Ticket's own agent or a resolver
   * on the Ticket's conflicted merge (issue #129).
   */
  liveAttempt: LiveAttemptRecord | null;
  /**
   * The ticket's Held pane (issue #139): while it waits at a checkpoint
   * Interrupt whose Terminal-backed attempt's pane is still alive in herdr,
   * that attempt's number and pane, so the card and the Detail keep peek,
   * focus and attach for it and offer Keep talking. Null once the Interrupt
   * is answered or the pane is gone, for a headless attempt, and for every
   * ticket not at a checkpoint. Never set together with `liveAttempt`.
   */
  heldPane: HeldPaneRecord | null;
  /**
   * The ticket was enlisted from a live herdr pane (issue #101): its
   * Assignment was recorded as found, so the card reads "as found" where a
   * spawned ticket names a model. Derived by the server from the marker's
   * durable `enlisted-from` field.
   */
  enlisted: boolean;
  /**
   * Reassign (issue #126): whether a write to this ticket's assign entry
   * would take effect at the next boundary, why not when it would not, the
   * ticket's own verify count, and where each field of `assignment` came
   * from. For a ticket with no Attempt in flight, `assignment` is resolved
   * from the config file as it stands now, so a Reassign shows on the card
   * at once rather than at the next boundary; an in-flight ticket keeps
   * the engine's frozen record.
   */
  reassign: TicketReassignView;
}

/** The pool's state as the Console sees it: the engine's snapshot enriched by the server. */
export interface EnrichedSnapshot {
  seq: number;
  phase: RunPhase;
  /** The pool's display name: the last two path segments of the pool directory. */
  poolName: string;
  /**
   * The Pool title (issue #100) from the pool's config as it stands now, or
   * null when it has none; the Console shows it ahead of `poolName`, which
   * it falls back to. Display-only: the directory stays the identity.
   */
  poolTitle: string | null;
  /**
   * The pool directory the server was launched on, verbatim: what a
   * relaunch after a Console stop (issue #97) passes to `--pool`.
   */
  poolDir: string;
  /**
   * Finished terminals (issue #139): how many herdr tabs this pool opened
   * are still open over an Attempt or a Conversation that has ended, none
   * of them a Live attempt's, a Held pane's, an enlisted pane or a live
   * Conversation's. The pool header offers to close them when it is not 0;
   * the engine never closes them on its own.
   */
  finishedTerminals: number;
  /**
   * The Spawn caps in force and this run's count (issue #149), from the
   * engine's snapshot verbatim: "Spawns `spawnedThisRun`/`perRun` this run"
   * and "`perAttempt` per attempt". A run is this Console boot.
   */
  spawnUsage: SpawnUsage;
  /**
   * The Pending spawns (issue #150), oldest first, from the engine's
   * snapshot verbatim: proposals within the caps that land at the next
   * super-step boundary unless the operator Holds or Discards them first.
   */
  pendingSpawns: PendingSpawnView[];
  /**
   * The Held spawns (issue #149, ADR-0029, widened by issue #150), oldest
   * first, from the engine's snapshot verbatim: the proposals a Spawn cap
   * had no room for, the agent marked as overlapping, or the operator held
   * back, each waiting for the operator to Adopt it (past the caps) or
   * Discard it.
   */
  heldSpawns: HeldSpawnView[];
  /**
   * The Steward budget (ADR-0030), from the engine's snapshot verbatim: the
   * Pool's budget per Ticket, and what the Steward has used on each Ticket
   * it answered since the operator last did (absent from `used` is 0).
   * Remaining is `budget - used`. Always sent; optional only so a fixture
   * written before the Steward still types.
   */
  stewardBudget?: StewardBudgetView;
  state: {
    tickets: EnrichedTicketState[];
    /**
     * Every Conversation the pool knows about (issue #60), passed through
     * from the engine's own snapshot verbatim: conversationViewOf already
     * builds the wire shape the UI wants, so there is nothing to enrich.
     */
    conversations: ConversationView[];
    log: string[];
    outcomes: Record<string, Outcome>;
    interrupts: Interrupt[];
    /**
     * The Merge queue (issue #129): every held ticket, head first, in the
     * order the engine works through them. Empty when no hold stands.
     */
    mergeQueue: MergeQueueEntry[];
    /** Accepted answers still waiting for processing (the Queued answers). */
    queuedAnswers: QueuedAnswer[];
    config: Record<string, unknown>;
  };
}

// ---------------------------------------------------------------------------
// Ticket events (GET /api/events)
// ---------------------------------------------------------------------------

/** An attempt rebuilt from its log file, for a ticket with no events file. */
export interface ReconstructedAttempt {
  attempt: number;
  logFile: string;
  modifiedAt: string;
}

/** GET /api/events's answer. */
export interface TicketEventsResponse {
  events: TicketEvent[];
  attempts: ReconstructedAttempt[];
  reconstructed: boolean;
  /** The ticket's spec text: the issue file body after the title heading. */
  spec: string;
}

// ---------------------------------------------------------------------------
// Ticket log (GET /api/log)
// ---------------------------------------------------------------------------

/** One attempt a ticket's log can be read for. */
export interface LogAttemptInfo {
  attempt: number;
  kind: "implement" | "resolver" | "reconstructed";
  current: boolean;
  logFile: string;
  /**
   * The attempt's Stream file (the raw stream tee, ADR-0012), named by the
   * events module's contract the same way `logFile` is. Null when the
   * attempt has no Stream file on disk: a raw harness (opencode), a
   * pre-streaming attempt, or a reconstructed row.
   */
  streamFile: string | null;
}

/** GET /api/log's answer: one byte range of an attempt's log or Stream file. */
export interface TicketLogResponse {
  content: string;
  offset: number;
  nextOffset: number;
  totalSize: number;
  attempts: LogAttemptInfo[];
}

// ---------------------------------------------------------------------------
// Ticket activity (GET /api/activity)
// ---------------------------------------------------------------------------

/** GET /api/activity's answer, and the socket's live activity value. */
export interface TicketActivityResponse {
  ticketId: string;
  running: boolean;
  diff: { added: number; removed: number; files: string[] } | null;
  log: { size: number; mtime: string } | null;
  lastEventAt: string | null;
}

// ---------------------------------------------------------------------------
// Grades (GET /api/grades)
// ---------------------------------------------------------------------------

/**
 * One ticket's latest grade, as the card summaries show it: the score and
 * verdict with the graded attempt's number, plus the winning attempt's
 * number once Selection has named one. Derived at read time from the same
 * events files the Detail's timeline reads, so a card and the Detail never
 * disagree. Reasons stay in the events payload; the card is a summary.
 */
export interface TicketGradeSummary {
  attempt: number;
  score: number;
  verdict: string;
  /**
   * The attempt Selection named, or the merged attempt on a ticket graded
   * before the selection machinery. Null until either event lands. The
   * Detail's winner badge reads this field, so both surfaces share the one
   * derivation.
   */
  winner: number | null;
}

// ---------------------------------------------------------------------------
// Ticket body (GET /api/ticket)
// ---------------------------------------------------------------------------

/** GET /api/ticket's answer. */
export interface TicketBodyResponse {
  id: string;
  /** The Issue file's markdown with the line-1 state marker stripped. */
  body: string;
}

// ---------------------------------------------------------------------------
// Keep talking (POST /api/keep-talking)
// ---------------------------------------------------------------------------

/**
 * Keep talking (issue #139): continue a ticket's checkpointed Attempt in its
 * Held pane. Not a resume action: it is never queued for the super-step
 * boundary (ADR-0004's exception, as Enlist is), so it has its own route.
 */
export interface KeepTalkingRequest {
  ticketId: string;
}

/**
 * The Continued attempt's number, once the engine has claimed the pane. A
 * refusal is the 409 `reason` envelope the enlist route answers with.
 */
export interface KeepTalkingResponse {
  ticketId: string;
  attempt: number;
}

// ---------------------------------------------------------------------------
// Close finished terminals (POST /api/terminals/close-finished)
// ---------------------------------------------------------------------------

/** How many Finished terminals the bulk close closed. */
export interface CloseFinishedTerminalsResponse {
  closed: number;
}

// ---------------------------------------------------------------------------
// Held spawns (POST /api/spawns/held/adopt, /api/spawns/held/discard)
// ---------------------------------------------------------------------------

/**
 * Adopt or Discard one Held spawn (issue #149, ADR-0029), by its id. Adopt
 * answers 202 once the adoption is queued (written at once on an idle pool,
 * at the next boundary otherwise); Discard answers 200 once it is gone. A
 * refusal is the 409 `reason` envelope the keep-talking route answers with.
 */
export interface HeldSpawnRequest {
  id: string;
}

/** The Held spawn an Adopt or Discard acted on. */
export interface HeldSpawnResponse {
  id: string;
}

// ---------------------------------------------------------------------------
// Pending spawns (POST /api/spawns/pending/hold, /api/spawns/pending/discard)
// ---------------------------------------------------------------------------

/**
 * Hold or Discard one Pending spawn before the boundary lands it (issue
 * #150), by its id. Hold answers 200 once it is a Held spawn (held by the
 * operator, same id); Discard answers 200 once it is gone. One that has
 * already landed, or is not pending, is refused with the 409 `reason`
 * envelope.
 */
export interface PendingSpawnRequest {
  id: string;
}

/** The Pending spawn a Hold or Discard acted on. */
export interface PendingSpawnResponse {
  id: string;
}

// ---------------------------------------------------------------------------
// Terminal peek (GET /api/terminal/peek)
// ---------------------------------------------------------------------------

/**
 * The peek endpoint's answer for one ticket: the pane's viewport as plain
 * text (ANSI stripped herdr-side), the engine's own last read of it when a
 * loop of the engine's watches the pane and a live viewport read otherwise
 * (issue #122). The UI keys every terminal call by ticket id; the server
 * resolves and guards the pane, and which of the two served it is not the
 * UI's concern.
 */
export interface TerminalPeekResponse {
  ticket: string;
  paneId: string;
  text: string;
}
