#!/usr/bin/env bash
set -euo pipefail

# NOTE: This is a dev-only script, intended for use by maintainers of this repo.
# It is not a supported installer. Modifications to it, or requests for
# modifications, will not be approved.
#
# Links every skill in this repo (SKILL.md, excluding deprecated/) into the
# local skill directories used by each agent harness:
#   - ~/.claude/skills: Claude Code (symlink)
#   - ~/.agents/skills: Codex and other Agent Skills-compatible harnesses (symlink)
#   - ~/.cursor/skills: Cursor (real copy, because its picker won't follow symlinks,
#     stamped with a .linked-from marker so cross-repo pruning stays safe)
#   - ~/.config/opencode/command: OpenCode slash-command stubs
# The symlinked entries point into this repo, so a `git pull` is all that's
# needed to keep those installed skills up to date. Cursor's copies and the
# opencode stubs are refreshed by re-running this script.
#
# Idempotent. Re-run after adding, renaming, or removing a skill.

REPO="$(cd "$(dirname "$0")/.." && pwd)"
CURSOR_DEST="$HOME/.cursor/skills"
DESTS=("$HOME/.claude/skills" "$HOME/.agents/skills" "$CURSOR_DEST")
CONFIG_DIR="${OPENCODE_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/opencode}"
COMMAND_DIR="$CONFIG_DIR/command"

# Stamped into every generated opencode stub so pruning only ever deletes our
# own stubs and leaves hand-written commands alone. Deliberately differs from
# the ~/.claude/commands/scripts/link-opencode-commands.sh marker so neither
# script prunes the other's stubs.
MARKER="<!-- generated by agent-console link-skills.sh -->"

# Prints NUL-separated paths to every SKILL.md in the repo, excluding
# node_modules, .git and deprecated.
repo_skill_files() {
  find "$REPO" -name SKILL.md \
    -not -path '*/node_modules/*' \
    -not -path '*/.git/*' \
    -not -path '*/deprecated/*' \
    -print0
}

# Names of current repo skills, one per line.
repo_skill_names() {
  repo_skill_files | while IFS= read -r -d '' skill_md; do
    basename "$(dirname "$skill_md")"
  done
}
VALID_NAMES="$(repo_skill_names)"

guard_dest() {
  local dest="$1"
  if [ -L "$dest" ]; then
    local resolved
    resolved="$(readlink -f "$dest")"
    case "$resolved" in
      "$REPO"|"$REPO"/*)
        echo "error: $dest is a symlink into this repo ($resolved)." >&2
        echo "Remove it (rm \"$dest\") and re-run; the script will recreate it as a real dir." >&2
        exit 1
        ;;
    esac
  fi
  mkdir -p "$dest"
}

link_skill() {
  local src="$1" name="$2"
  for dest in "${DESTS[@]}"; do
    local target="$dest/$name"
    if [ "$dest" = "$CURSOR_DEST" ]; then
      # Cursor's slash-command picker does not follow symlinks; it needs real
      # dirs. Drop any prior symlink/dir and copy so the picker sees the skill.
      # The .linked-from marker records the source so a later prune can tell
      # this repo's copies apart from another repo's.
      rm -rf "$target"
      cp -R "$src" "$target"
      printf '%s\n' "$src" > "$target/.linked-from"
      echo "copied $name -> $src ($dest)"
    else
      if [ -e "$target" ] && [ ! -L "$target" ]; then
        rm -rf "$target"
      fi
      ln -sfn "$src" "$target"
      echo "linked $name -> $src ($dest)"
    fi
  done
}

prune_stale() {
  local dest="$1"
  for target in "$dest"/*; do
    [[ -e "$target" || -L "$target" ]] || continue
    local name resolved
    name="$(basename "$target")"
    if [[ -L "$target" ]]; then
      # Plain readlink, not -f/-m: we link with absolute repo paths, so the
      # stored value is already what we want to match, and reading it does not
      # require the target to still exist. -f returns nothing once the target is
      # gone, and -m is GNU-only (it fails outright on macOS) — either way
      # `resolved` ends up empty and orphan links survive forever.
      resolved="$(readlink "$target" 2>/dev/null || true)"
      case "$resolved" in
        "$REPO"/*)
          if [[ ! -f "$resolved/SKILL.md" ]]; then
            rm "$target"
            echo "removed orphan $name ($dest)"
          fi
          ;;
      esac
    elif [[ "$dest" = "$CURSOR_DEST" && -d "$target" && -f "$target/SKILL.md" ]]; then
      # Cursor copies are real dirs, not symlinks: stale only if this repo made
      # them (.linked-from points into $REPO) and the name is no longer a
      # current repo skill. Dirs without our marker, or stamped by another
      # repo's linker, belong to that linker and are left alone.
      local from=""
      if [ -f "$target/.linked-from" ]; then
        from="$(cat "$target/.linked-from")"
      fi
      case "$from" in
        "$REPO"|"$REPO"/*)
          if ! grep -qxF "$name" <<<"$VALID_NAMES"; then
            rm -rf "$target"
            echo "removed stale $name ($dest)"
          fi
          ;;
      esac
    fi
  done
}

for dest in "${DESTS[@]}"; do
  guard_dest "$dest"
  prune_stale "$dest"
done

while IFS= read -r -d '' skill_md; do
  src="$(dirname "$skill_md")"
  name="$(basename "$src")"
  link_skill "$src" "$name"
done < <(repo_skill_files)

if ! command -v opencode >/dev/null 2>&1 \
  && [ ! -x "$HOME/.opencode/bin/opencode" ] \
  && [ ! -d "$CONFIG_DIR" ]; then
  echo "opencode not installed — skipping command generation"
  exit 0
fi

# Prints a SKILL.md's frontmatter `description`, folded onto one line and escaped
# for use inside a double-quoted YAML scalar. Handles plain, quoted and block
# (| and >) scalars. OpenCode refuses to start if any command file has invalid
# frontmatter, so the output is always re-escaped rather than passed through.
skill_description() {
  awk '
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t\r]+$/, "", s); return s }
    BEGIN { bs = sprintf("%c", 92); dq = sprintf("%c", 34); sq = sprintf("%c", 39) }
    NR == 1 { if ($0 !~ /^---[ \t\r]*$/) exit; next }
    /^(---|\.\.\.)[ \t\r]*$/ { exit }
    !capturing && /^description:/ {
      val = trim(substr($0, 13))
      if (val ~ /^[|>][0-9+-]*$/) val = ""   # block scalar header; body follows
      capturing = 1
      next
    }
    capturing {
      # Continuation lines are indented (or blank); anything at column 0 is the
      # next key.
      if ($0 ~ /^[ \t]/ || trim($0) == "") {
        line = trim($0)
        if (line != "") val = (val == "" ? line : val " " line)
        next
      }
      capturing = 0
    }
    END {
      gsub(/[\t\r]/, " ", val)
      gsub(/ +/, " ", val)
      val = trim(val)

      n = length(val)
      if (n >= 2) {
        first = substr(val, 1, 1); last = substr(val, n, 1)
        if (first == dq && last == dq) {
          val = substr(val, 2, n - 2)
          gsub(bs bs dq, dq, val)
          gsub(bs bs bs bs, bs bs, val)
        } else if (first == sq && last == sq) {
          val = substr(val, 2, n - 2)
          gsub(sq sq, sq, val)
        }
      }

      # OpenCode truncates long palette entries anyway.
      if (length(val) > 200) val = trim(substr(val, 1, 197)) "..."

      out = ""
      for (i = 1; i <= length(val); i++) {
        c = substr(val, i, 1)
        if (c == bs || c == dq) out = out bs
        out = out c
      }
      print out
    }
  ' "$1"
}

render_stub() {
  local src="$1" desc="$2"
  cat <<EOF
---
description: "$desc"
---
$MARKER
Read \`$src/SKILL.md\` in full and follow it as your instructions for this task.

Resolve any relative paths it mentions against \`$src/\`.

The user's input, which may be empty:

\$ARGUMENTS
EOF
}

mkdir -p "$COMMAND_DIR"

WRITTEN=""
while IFS= read -r -d '' skill_md; do
  src="$(dirname "$skill_md")"
  name="$(basename "$src")"
  desc="$(skill_description "$skill_md")"
  [ -n "$desc" ] || desc="Run the $name skill."

  out="$COMMAND_DIR/$name.md"
  new="$(render_stub "$src" "$desc")"
  if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
    printf '%s\n' "$new" > "$out"
    echo "wrote $name -> $src ($COMMAND_DIR)"
  fi
  WRITTEN="$WRITTEN$name"$'\n'
done < <(repo_skill_files)

for f in "$COMMAND_DIR"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .md)"
  if ! grep -qxF "$name" <<<"$WRITTEN"; then
    if grep -qF "$MARKER" "$f"; then
      rm "$f"
      echo "removed stale $name ($COMMAND_DIR)"
    fi
  fi
done
